#!/usr/bin/env sh
FILE=commit.cmd
if test -f "$FILE"; then
    echo "$FILE exists."
    rm commit.cmd
    exit 0;
fi
#// if on Windows, spwan a cmd that will run npx cz
case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*)
        echo "npx cz && exit" > commit.cmd
        start commit.cmd
    exit 1;;
esac
. "$(dirname "$0")/_/husky.sh"
exec < /dev/tty 2>&1 && npx cz --hook || true
